# Site settings
title: pradeek's blog
description: "This is my technical blog site"
baseurl: "/pradeeks-blog"
url: "https://pradeekyahvi.github.io/pradeeks-blog"
tagline: tech blog

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
gems :
  - jekyll-paginate
