# Site settings
title: codelogs
description: "knowledge is power and should be free"
baseurl: ""
url: ""
tagline: programming and technical blog.

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
plugins :
  - jekyll-paginate
